input UserInput {
  id: Long!
  fullName: String
  email: String
  token: String
  password: String
  image: String
}

input TaskInput {
  title: String!
  description: String!
  taskStatus: String!
  taskPriority: String!
  users: [UserInput!]
}

type Task {
  id: Long!
  title: String!
  description: String!
  taskStatus: String!
  taskPriority: String!
  version: Int!
  taskOrder: Int!
  users: [User!]
}

type User {
  id: ID
  email: String
  fullName: String
  token: String
  password: String
  image: String
}

type Query {
    getTaskById(id: Long!): Task!
    getTasks(limit: Int!, offset: Int!, description: String): [Task!]!
}

type Mutation {
    createTask(task: TaskInput!): Task
    updateTask(id: Long!, task: TaskInput!): Task
    deleteTask(id: Long!, version: Int!): Task
    dragTask(taskId: Int!, taskStatus: String!, taskOrder: Int!, taskVersion: Int): OptionalTask
}
