quarkus.application.name=Kanban-Board
quarkus.http.port=3033
quarkus.http.host=0.0.0.0
quarkus.http.limits.max-header-size=1M
quarkus.http.limits.max-body-size=10M

frontend.app.port=4202
app.environment=localhost

token.duration.in.hours=2

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=Cica1206!
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/shema2?connectionTimeZone=UTC&serverTimezone=UTC&useSSL=false
quarkus.datasource.jdbc.max-size=16

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.dialect=org.hibernate.dialect.MySQL8Dialect
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.jdbc.timezone=UTC

quarkus.log.category."org.springframework.graphql".level=DEBUG
quarkus.log.category."com.graphql".level=DEBUG
quarkus.log.category."org.springframework.web.socket".level=DEBUG
quarkus.log.category."org.springframework.messaging.simp".level=DEBUG

requests.max.requests.in.one.minute=60

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:4200,http://localhost:4202,http://127.0.0.1:4200,http://127.0.0.1:4202,http://192.168.0.26:4200,http://192.168.0.26:4202,http://0.0.0.0:4200,http://0.0.0.0:4202
quarkus.http.cors.methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
quarkus.http.cors.headers=*
quarkus.http.cors.access-control-allow-credentials=true
quarkus.http.cors.access-control-max-age=3600

